---
- name: Install VirtualBox
  become: yes
  package:
    name:
      - virtualbox
      - virtualbox-host-modules-arch
    state: present

- name: Install VirtualBox Extension Pack
  become: yes
  become_user: aurbuilder
  aur:
    name: virtualbox-ext-oracle
    use: "{{ aur_helper }}"
    state: present

- name: Add user to VirtualBox group
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    groups:
      - vboxusers
    append: yes

- name: Install libvirt
  become: yes
  package:
    name:
      - bridge-utils
      - dnsmasq
      - ebtables
      - edk2-ovmf
      - openbsd-netcat
      - qemu
      - virt-manager
    state: present

- name: Enable libvirt service
  become: yes
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: Add user to libvirt group
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    groups:
      - libvirt
    append: yes

- name: Install Vagrant
  become: yes
  package:
    name: vagrant
    state: present
